### ISSUE TITLE
array_it_length function resets current position in iterator

### ISSUE THREAD

**Issue by Jasper-Ben** [jaksonlabs/jakson#2]
see : [https://codedocs.xyz/jaksonlabs/jakson/array__it_8c_source.html#l00199](https://codedocs.xyz/jaksonlabs/jakson/array__it_8c_source.html#l00199)
as we rewind the array iterator and don't reset it afterwards to the previous position, this function is not safe. Is this intended behavior? I understand, that this might remove the need to clone an array iterator, but isn't very developer friendly.

**Comment by pinnecke** [comment]
Fixed with commit bc396d9
